const TYPES = {
  LOGIN_REQUEST: '',
  LOGIN_SUCCESS: '',
  LOGIN_FAILURE: '',

  LOGOUT: '',

  TOGGLE_MENU: '',

  GET_PROFILE_REQUEST: '',
  GET_PROFILE_SUCCESS: '',
  GET_PROFILE_FAILURE: '',

  EDIT_PROFILE: '',

  PATCH_PROFILE_REQUEST: '',
  PATCH_PROFILE_SUCCESS: '',
  PATCH_PROFILE_FAILURE: '',

  GET_HOME_EVENT_LIVE_REQUEST: '',
  GET_HOME_EVENT_LIVE_SUCCESS: '',
  GET_HOME_EVENT_LIVE_FAILURE: '',

  GET_EVENTS_COMING_UP_REQUEST: '',
  GET_EVENTS_COMING_UP_SUCCESS: '',
  GET_EVENTS_COMING_UP_FAILURE: '',

  GET_EVENTS_PAST_REQUEST: '',
  GET_EVENTS_PAST_SUCCESS: '',
  GET_EVENTS_PAST_FAILURE: '',

  GET_EVENT_DETAILS_REQUEST: '',
  GET_EVENT_DETAILS_SUCCESS: '',
  GET_EVENT_DETAILS_FAILURE: '',

  GET_EVENT_SCHEDULES_REQUEST: '',
  GET_EVENT_SCHEDULES_SUCCESS: '',
  GET_EVENT_SCHEDULES_FAILURE: '',
};

Object.keys(TYPES).map(key => {
  TYPES[key] = key;
});

export { TYPES };

export default TYPES;
